DROP TABLESPACE DBJXGX INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE DBJXGX_TEMP INCLUDING CONTENTS AND DATAFILES;
DROP USER U_JXGK CASCADE;

CREATE TABLESPACE DBJXGX LOGGING DATAFILE 'c:/data/JXGK/MAIN.dbf' SIZE 500M AUTOEXTEND ON NEXT 200M MAXSIZE 2048M;
CREATE TEMPORARY TABLESPACE DBJXGX_TEMP TEMPFILE 'c:/data/JXGK/TEMP.dbf' SIZE 100M AUTOEXTEND ON NEXT 32M MAXSIZE 500M;
CREATE USER U_JXGK IDENTIFIED BY ORCL DEFAULT TABLESPACE DBJXGX TEMPORARY TABLESPACE DBJXGX_TEMP;
GRANT CONNECT,RESOURCE TO U_JXGK;